import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThirdwebProvider } from './components/thirdweb-client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThirdwebProvider clientId='ADD_YOUR_CLIENT_ID_HERE' activeChain={'ethereum'}>
					{children}
				</ThirdwebProvider>
			</body>
		</html>
	);
}
